Repository bluebanquise/bluebanquise, pull requests merged in 2020-10, with the labels that each got.

#404 fix: ensure selinux type is correct on diskless directories
  roles/addons/diskless/tasks/main.yml
Labels: needs-backport

#405 Fix: documentation - corrections based on feedback
  resources/documentation/install_first_management.rst
Labels: bug, documentation

#406 Fix: hosts_file - Prevent massive empty lines generation
  roles/core/hosts_file/templates/hosts.j2
Labels: bug, needs-backport

#408 [master] [advanced_dhcp_server] whitespace too long, buffer overflow.
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: bug, needs-backport

#401 Oxedions/feat/nmcli
  CHANGELOG.md
  roles/addons/nic_nmcli/tasks/main.yml
Labels: bug, enhancement

#395 Feat: Adding ssh ProxyJump to ssh_master template
  CHANGELOG.md
  roles/core/ssh_master/defaults/main.yml
  roles/core/ssh_master/molecule/default/molecule.yml
  roles/core/ssh_master/readme.rst
  roles/core/ssh_master/templates/config.j2
Labels: enhancement

#417 ci: run ansible-lint on whole project tree
  .github/workflows/static_analysis.yml
  CHANGELOG.md
  resources/packaging/bluebanquise.spec
  roles/addons/Lmod/templates/modules_extra_path.sh.j2
  roles/addons/Lmod/vars/RedHat.yml
  roles/addons/clone/tasks/main.yml
  roles/addons/lmod/readme.rst
  roles/addons/lmod/tasks/main.yml
  roles/addons/lmod/templates/modules_extra_path.sh.j2
  roles/addons/lmod/vars/RedHat.yml
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/prometheus_server/tasks/main.yml
  roles/addons/sssd/tasks/main.yml
  roles/core/ssh_master/molecule/default/prepare.yml
Labels: ci/cd

#423 fix: use regex to replace kernel in boot.ipxe
  roles/addons/diskless/files/disklessset.py
Labels: bug, needs-backport

#425 fix: use regex to replace kernel in boot.ipxe
  roles/addons/diskless/files/disklessset.py
Labels: backport, bug

#414 Fix: CHANGELOG.md - Add missing entries
  CHANGELOG.md
Labels: bug, documentation, enhancement

#424 Doc: Diskless - Improve the readme
  roles/addons/diskless/readme.rst
Labels: bug, documentation

#431 Fix: core/nic - Update readme
  roles/core/nic/readme.rst
Labels: bug, documentation

#437 Doc: Inform that some exporter are not provided as packages
  resources/documentation/monitoring/ha_cluster_exporter.rst
  resources/documentation/monitoring/slurm_exporter.rst
  roles/addons/prometheus_client/readme.rst
Labels: documentation

#427 doc: improve diskless readme
  roles/addons/diskless/readme.rst
Labels: backport

#426 Feat: pxe_stack - Add fbtftp for RHEL/CentOS 8
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/tasks/main.yml
  roles/core/pxe_stack/vars/RedHat_7.yml
  roles/core/pxe_stack/vars/RedHat_8.yml
  roles/core/pxe_stack/vars/Ubuntu.yml
Labels: enhancement

#442 Fix: core/pxe_stack - Allow to disable clone entries in menu
  roles/addons/clone/readme.rst
  roles/core/pxe_stack/defaults/main.yml
  roles/core/pxe_stack/templates/menu.ipxe.j2
Labels: enhancement

#441 Fix: core/dhcp_server|adv_core/adv_dhcp_server up readme
  roles/advanced-core/advanced_dhcp_server/readme.rst
  roles/core/dhcp_server/readme.rst
Labels: bug, documentation

#398 ci: run molecule test with tox
  .github/workflows/molecule-actions-addons-clustershell.yml
  .github/workflows/molecule-actions-addons-grafana.yml
  .github/workflows/molecule-actions-addons-root_password.yml
  .github/workflows/molecule-actions-addons-users_basic.yml
  .github/workflows/molecule-actions-core-bluebanquise.yml
  .github/workflows/molecule-actions-core-conman.yml
  .github/workflows/molecule-actions-core-display_tuning.yml
  .github/workflows/molecule-actions-core-dns_client.yml
  .github/workflows/molecule-actions-core-dns_server.yml
  .github/workflows/molecule-actions-core-firewall.yml
  .github/workflows/molecule-actions-core-log_client.yml
  .github/workflows/molecule-actions-core-log_server.yml
  .github/workflows/molecule-actions-core-repositories_client.yml
  .github/workflows/molecule-actions-core-ssh_master.yml
  .github/workflows/molecule-actions-core-time.yml
  roles/addons/clustershell/molecule/default/molecule.yml
  roles/addons/grafana/molecule/default/molecule.yml
  roles/addons/root_password/molecule/default/molecule.yml
  roles/addons/users_basic/molecule/default/molecule.yml
  roles/advanced-core/advanced_dns_server/molecule/default/molecule.yml
  roles/advanced-core/advanced_dns_server/molecule/default/verify.yml
  roles/core/bluebanquise/molecule/default/molecule.yml
  roles/core/bluebanquise/molecule/default/verify.yml
  roles/core/display_tuning/molecule/default/molecule.yml
  roles/core/display_tuning/molecule/default/verify.yml
  roles/core/dns_client/molecule/default/molecule.yml
  roles/core/dns_client/molecule/default/verify.yml
  roles/core/dns_server/molecule/default/molecule.yml
  roles/core/dns_server/molecule/default/verify.yml
  roles/core/firewall/molecule/default/molecule.yml
  roles/core/log_client/molecule/default/molecule.yml
  roles/core/log_server/molecule/default/molecule.yml
  roles/core/time/molecule/default/converge.yml
  roles/core/time/molecule/default/molecule.yml
  tox.ini
Labels: ci/cd

#451 ci: test timezone is 'Europe/Paris'
  roles/core/time/molecule/default/verify.yml
Labels: ci/cd, needs-backport

#449 Fix: core/dns_server - Missing bmc alias
  roles/core/dns_server/templates/forward.j2
Labels: bug, needs-backport

#450 Fix: adv_core/adv_dns_server
  roles/advanced-core/advanced_dns_server/templates/forward.j2
Labels: bug, needs-backport

#438 ci: add advanced_dns_server molecule test
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-advanced_core-advanced_dns_server.yml
  roles/advanced-core/advanced_dns_server/molecule/default/converge.yml
Labels: ci/cd

#459 ci: test timezone is 'Europe/Paris'
  roles/core/time/molecule/default/converge.yml
  roles/core/time/molecule/default/verify.yml
Labels: backport
