Repository bluebanquise/bluebanquise, pull requests merged in 2020-05, with the labels that each got.

#206 backport gpg support
  inventory/group_vars/all/general_settings/external.yml
  inventory/group_vars/all/general_settings/repositories.yml
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
Labels: backport

#204 Feat: Add post and pre script ability to autoinstall
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  roles/core/pxe_stack/templates/kickstart.cfg.j2
Labels: enhancement

#203 Fix: fix small issues in documentation
  resources/documentation/configure_bluebanquise.rst
  resources/documentation/deploy_bluebanquise.rst
  resources/documentation/install_first_management.rst
  resources/documentation/learn_ansible.rst
  resources/documentation/vocabulary.rst
  roles/core/pxe_stack/readme.rst
Labels: bug, documentation

#208 feat: add venv-molecule directory to .gitignore
  .gitignore
Labels: enhancement

#201 feat: dns server slaves
  .github/workflows/molecule-actions.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice1-1.yml
  resources/examples/simple_cluster/playbooks/management1.yml
  roles/advanced-core/advanced_dhcp_server/readme.rst
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2
  roles/advanced-core/advanced_dhcp_server/vars/main.yml
  roles/core/ansible/readme.rst
  roles/core/ansible/tasks/main.yml
  roles/core/ansible/vars/main.yml
  roles/core/dhcp_server/readme.rst
  roles/core/dhcp_server/templates/dhcpd.networks.conf.j2
  roles/core/dhcp_server/vars/main.yml
  roles/core/dns_client/readme.rst
  roles/core/dns_client/templates/resolv.conf.j2
  roles/core/dns_client/vars/main.yml
  roles/core/dns_server/molecule/default/converge.yml
  roles/core/dns_server/molecule/default/molecule.yml
  roles/core/dns_server/readme.rst
  roles/core/dns_server/tasks/main.yml
  roles/core/dns_server/tasks/master.yml
  roles/core/dns_server/templates/forward.j2
  roles/core/dns_server/templates/forward.soa.j2
  roles/core/dns_server/templates/named.conf.j2
  roles/core/dns_server/templates/reverse.j2
  roles/core/dns_server/templates/reverse.soa.j2
  roles/core/dns_server/vars/main.yml
Labels: ci/cd, enhancement

#212 Feat: enhance repositories
  resources/documentation/install_first_management.rst
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_SMP/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_compute/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_login/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeC/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeL/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeM/equipment_profile.yml
  roles/core/pxe_stack/files/osdeploy/centos_7.ipxe
  roles/core/pxe_stack/files/osdeploy/centos_8.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/templates/configuration_centos.ipxe.j2
  roles/core/pxe_stack/templates/equipment_profile.ipxe.j2
  roles/core/pxe_stack/vars/main.yml
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/opensuse_leap_15.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
  roles/core/repositories_client/templates/environment.j2
  roles/core/repositories_client/templates/releasever.j2
  roles/core/repositories_client/vars/main.yml
  roles/core/repositories_server/readme.rst
Labels: enhancement

#215 fix: use management_networks_naming in dns_server
  roles/core/dns_server/molecule/default/converge.yml
  roles/core/dns_server/tasks/main.yml
Labels: bug

#210 fix: multiple issues with time role (#166)
  .github/workflows/molecule-actions-core-time.yml
  .github/workflows/molecule-actions.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml
  resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml
  roles/core/time/molecule/default/converge.yml
  roles/core/time/molecule/default/molecule.yml
  roles/core/time/molecule/default/verify.yml
  roles/core/time/readme.rst
  roles/core/time/templates/chrony.conf.j2
Labels: bug, ci/cd

#218 feat: add inventory and playbooks to .gitignore
  .gitignore
Labels: enhancement

#221 Feat: rename role ansible to bluebanquise
  .github/workflows/molecule-actions-core-bluebanquise.yml
  resources/documentation/deploy_bluebanquise.rst
  resources/examples/simple_cluster/playbooks/management1.yml
  roles/core/bluebanquise/.yamllint
  roles/core/bluebanquise/molecule/default/INSTALL.rst
  roles/core/bluebanquise/molecule/default/converge.yml
  roles/core/bluebanquise/molecule/default/molecule.yml
  roles/core/bluebanquise/molecule/default/prepare.yml
  roles/core/bluebanquise/molecule/default/verify.yml
  roles/core/bluebanquise/readme.rst
  roles/core/bluebanquise/tasks/main.yml
  roles/core/bluebanquise/vars/RedHat_7.yml
  roles/core/bluebanquise/vars/RedHat_8.yml
  roles/core/bluebanquise/vars/Ubuntu.yml
  roles/core/bluebanquise/vars/main.yml
Labels: ci/cd, documentation, enhancement

#225 fix: gather OS vars in addons roles
  roles/addons/diskless/tasks/main.yml
  roles/addons/diskless/vars/RedHat.yml
  roles/addons/diskless/vars/Ubuntu.yml
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/nic_nmcli/vars/RedHat_7.yml
  roles/addons/nic_nmcli/vars/RedHat_8.yml
  roles/addons/nic_nmcli/vars/Ubuntu.yml
  roles/addons/nic_nmcli/vars/main.yml
  roles/addons/slurm/tasks/main.yml
  roles/addons/slurm/vars/RedHat.yml
  roles/addons/slurm/vars/Ubuntu.yml
  roles/addons/slurm/vars/main.yml
Labels: enhancement

#223 Fix: conman template issue
  roles/core/conman/templates/conman.conf.j2
Labels: backport, bug

#222 fix: use equipment_authentication in conman
  roles/core/conman/molecule/default/molecule.yml
  roles/core/conman/templates/conman.conf.j2
Labels: bug, needs-backport

#229 fix: use equipment_authentication in conman
  roles/core/conman/templates/conman.conf.j2
Labels: backport, bug

#230 Fix: log server seport deps
  roles/core/log_server/molecule/default/verify.yml
  roles/core/log_server/vars/RedHat_7.yml
  roles/core/log_server/vars/RedHat_8.yml
Labels: bug, needs-backport

#209 Fix: solve VLAN issues
  resources/examples/multi_icebergs_cluster/inventory/cluster/nodes/iceberg1/managements.yml
  roles/core/nic/readme.rst
  roles/core/nic/tasks/main.yml
  roles/core/nic/templates/ifcfg.j2
Labels: breaking change, bug, needs-backport

#233 backport VLAN/bonding fix
  inventory/cluster/nodes/iceberg1/managements.yml
  roles/advanced-core/advanced_nic/readme.rst
  roles/advanced-core/advanced_nic/tasks/main.yml
  roles/advanced-core/advanced_nic/tasks/main.yml.old
  roles/advanced-core/advanced_nic/templates/ifcfg.j2
Labels: backport, bug

#234 Fix molecule auto inclusion in documentation
  resources/documentation/conf.py
Labels: bug, documentation
