Repository bluebanquise/bluebanquise, pull requests merged in 2020-02, with the labels that each got.

#96 Fix: Fixing prometheus role
  roles/addons/prometheus_client/files/bb_exporter.py
  roles/addons/prometheus_client/files/bb_exporter_plugins/cpu.py
  roles/addons/prometheus_client/files/bb_exporter_plugins/mounted.py
  roles/addons/prometheus_client/files/bb_exporter_plugins/nhc.py
  roles/addons/prometheus_client/files/bb_exporter_plugins/ram.py
  roles/addons/prometheus_client/files/bb_exporter_plugins/services.py
  roles/addons/prometheus_client/files/bb_exporter_plugins/slurm.py
  roles/addons/prometheus_client/templates/bb_exporter.yml.j2
  roles/addons/prometheus_server/templates/ipmi_config.yml.j2
  roles/addons/prometheus_server/templates/prometheus.yml.j2
Labels: bug

#93 packaging: spec file to build bluebanquise RPMS
  bluebanquise.spec
  roles/addons/clone/files/clone.ipxe
  roles/addons/clone/files/deploy_clone.ipxe
Labels: enhancement

#99 fix: add support to enable and start services
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/ofed/tasks/main.yml
  roles/addons/ofed_sm/tasks/main.yml
  roles/addons/openldap_client/tasks/main.yml
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/prometheus_client/tasks/main.yml
  roles/addons/prometheus_server/tasks/main.yml
  roles/addons/slurm/tasks/main.yml
  roles/advanced-core/advanced_dhcp_server/tasks/main.yml
  roles/core/dns_server/tasks/services_centos_7.yml
  roles/core/dns_server/tasks/services_redhat_8.yml
  roles/core/dns_server/tasks/services_ubuntu_18.yml
  roles/core/nfs_client/tasks/main.yml
Labels: bug

#98 feat: create wrapper command bluebanquise-playbook
  bluebanquise.spec
  tools/bluebanquise-playbook
Labels: enhancement

#106 fix: add target variable to example playbooks
  resources/examples/simple_cluster/playbooks/login1.yml
  resources/examples/simple_cluster/playbooks/management1.yml
Labels: bug, enhancement

#104 [1.1.2] Trailing whitespace in dhcpd.subnet.conf.j2
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: bug

#108 [1.2.0] DHCPD doesn't work with multi-subnets and mutli-hosts
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: bug, enhancement

#105 [1.1.2] DHCPD doesn't work with multi-subnets and mutli-hosts
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: bug, enhancement

#103 Update all roles with tags template,service,package
  roles/advanced-core/advanced_dhcp_server/tasks/main.yml
Labels: bug, enhancement

#102 Update all roles with tags template,service,package
  roles/advanced-core/advanced_nic/tasks/main.yml
Labels: bug, enhancement

#118 [1.1.2] missing check in nfs client task
  roles/core/nfs_client/tasks/main.yml
Labels: bug

#114 [1.1.2] add start_services/enable_services in advanced_dhcp role
  roles/advanced-core/advanced_dhcp_server/tasks/main.yml
Labels: bug

#115 [1.2] change conman execpath
  roles/core/conman/templates/conman.conf.j2
Labels: bug

#116 [1.1.2] update conman execpath
  roles/core/conman/templates/conman.conf.j2
Labels: bug

#117 [1.2] missing check in nfs client task
  roles/core/nfs_client/tasks/main.yml
Labels: bug
