Repository bluebanquise/bluebanquise, pull requests merged in 2020-06, with the labels that each got.

#240 Fix: ansible_managed
  ansible.cfg
Labels: bug

#242 ci: setup molecule unit test for ssh_master role
  .github/workflows/molecule-actions-core-ssh_master.yml
  roles/core/ssh_master/.yamllint
  roles/core/ssh_master/molecule/default/INSTALL.rst
  roles/core/ssh_master/molecule/default/converge.yml
  roles/core/ssh_master/molecule/default/molecule.yml
  roles/core/ssh_master/molecule/default/prepare.yml
  roles/core/ssh_master/molecule/default/verify.yml
Labels: ci/cd

#246 Fix: remove customs/debug role from github
  roles/customs/debug/tasks/main.yml
  roles/customs/debug/templates/debug.j2
Labels: bug

#251 Add exclude parameter for RHEL and CentOS repositories in repository_client role
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
  roles/core/repositories_client/vars/main.yml
Labels: enhancement

#253 fix: use relative paths in ansible.cfg
  .github/workflows/static_analysis.yml
  ansible.cfg
Labels: enhancement

#254 ci: make output pretty and colorful
  .github/workflows/molecule-actions-addons-clustershell.yml
  .github/workflows/molecule-actions-addons-users_basic.yml
  .github/workflows/molecule-actions-core-bluebanquise.yml
  .github/workflows/molecule-actions-core-conman.yml
  .github/workflows/molecule-actions-core-display_tuning.yml
  .github/workflows/molecule-actions-core-dns_client.yml
  .github/workflows/molecule-actions-core-dns_server.yml
  .github/workflows/molecule-actions-core-log_client.yml
  .github/workflows/molecule-actions-core-log_server.yml
  .github/workflows/molecule-actions-core-repositories_client.yml
  .github/workflows/molecule-actions-core-ssh_master.yml
  .github/workflows/molecule-actions-core-time.yml
Labels: ci/cd

#257 Oxedions/feat/ni
  .gitignore
  CHANGELOG.md
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/j2_variables/README.md
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/j2_variables/accelerated_mode.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/j2_variables/equipment.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/j2_variables/groups.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/j2_variables/icebergs.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/j2_variables/network.yml
  resources/examples/simple_cluster/inventory/cluster/nodes/computes.yml
  resources/examples/simple_cluster/inventory/cluster/nodes/logins.yml
  resources/examples/simple_cluster/inventory/cluster/nodes/managements.yml
  resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/README.md
  resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/accelerated_mode.yml
  resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/equipment.yml
  resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/groups.yml
  resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/icebergs.yml
  resources/examples/simple_cluster/inventory/group_vars/all/j2_variables/network.yml
  roles/core/dhcp_server/readme.rst
  roles/core/dhcp_server/templates/dhcpd.subnet.conf.j2
  roles/core/dhcp_server/vars/main.yml
  roles/core/dns_server/molecule/default/molecule.yml
  roles/core/dns_server/tasks/main.yml
  roles/core/dns_server/templates/forward.j2
  roles/core/dns_server/templates/named.conf.j2
  roles/core/dns_server/templates/reverse.j2
  roles/core/hosts_file/readme.rst
  roles/core/hosts_file/tasks/main.yml
  roles/core/hosts_file/templates/hosts.j2
  roles/core/hosts_file/templates/macros
  roles/core/hosts_file/vars/main.yml
  roles/core/nic/readme.rst
  roles/core/nic/tasks/main.yml
  roles/core/nic/templates/ifcfg.j2
  roles/core/nic/vars/main.yml
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/templates/macros
  roles/core/pxe_stack/templates/nodes_parameters.yml.j2
  roles/core/pxe_stack/vars/main.yml
  roles/core/ssh_master/molecule/default/molecule.yml
  roles/core/ssh_master/readme.rst
  roles/core/ssh_master/templates/config.j2
  roles/core/ssh_master/templates/macros
  roles/core/ssh_master/vars/main.yml
  roles/core/time/molecule/default/molecule.yml
  roles/core/time/readme.rst
  roles/core/time/templates/chrony.conf.j2
  roles/core/time/templates/macros
  roles/core/time/vars/main.yml
  tools/inventory-converter-1.3-network_interfaces.py
Labels: breaking change, enhancement

#261 ci: remove Ubuntu 18.04 from molecule core/time
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-time.yml
Labels: bug, ci/cd

#266 fix: code cleanup in inventory converter helper
  tools/inventory-converter-1.3-network_interfaces.py
Labels: ci/cd
