Repository bluebanquise/bluebanquise, pull requests merged in 2020-09, with the labels that each got.

#362 fix: enhance performance of bootset at scale
  roles/core/pxe_stack/files/bootset.py
Labels: bug, needs-backport

#359 fix alias in hosts_file role
  roles/core/hosts_file/templates/hosts.j2
Labels: bug, needs-backport

#364 fix: enhance performance of bootset at scale (#362)
  roles/core/pxe_stack/files/bootset.py
Labels: backport

#363 fix alias in hosts_file role (#359)
  roles/core/hosts_file/templates/hosts.j2
Labels: backport

#354 Fix: Add equipment_profiles ability to diskless chroot
  roles/addons/diskless/readme.rst
Labels: bug, needs-backport

#365 Fix: Add equipment_profiles ability to diskless chroot (#354)
  roles/addons/diskless/readme.rst
Labels: backport

#348 feat: new addon role to install grafana
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-addons-grafana.yml
  resources/packaging/bluebanquise.spec
  roles/addons/grafana/.yamllint
  roles/addons/grafana/molecule/default/INSTALL.rst
  roles/addons/grafana/molecule/default/converge.yml
  roles/addons/grafana/molecule/default/molecule.yml
  roles/addons/grafana/molecule/default/prepare.yml
  roles/addons/grafana/readme.rst
  roles/addons/grafana/tasks/main.yml
  roles/addons/grafana/vars/RedHat.yml
Labels: enhancement

#361 add firewall to prometheus
  roles/addons/prometheus_client/tasks/main.yml
  roles/addons/prometheus_server/files/alertmanager.xml
  roles/addons/prometheus_server/handlers/main.yml
  roles/addons/prometheus_server/tasks/main.yml
Labels: bug, enhancement, needs-backport

#369 Fix: documentation - remove old syntax
  resources/documentation/learn_ansible.rst
Labels: bug, documentation

#368 fix: disable distro repos even when 'os' is a dict
  roles/core/repositories_client/molecule/default/molecule.yml
  roles/core/repositories_client/molecule/default/prepare.yml
  roles/core/repositories_client/molecule/default/verify.yml
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
Labels: bug, needs-backport

#367 fix: document variables in role slurm
  roles/addons/slurm/readme.rst
  roles/addons/slurm/tasks/main.yml
  roles/addons/slurm/templates/slurm.conf.j2
  roles/addons/slurm/vars/RedHat.yml
  roles/addons/slurm/vars/Ubuntu.yml
Labels: documentation, needs-backport

#370 Fix: diskless - readme
  roles/addons/diskless/readme.rst
Labels: bug, documentation

#373 fix: document variables in role slurm
  roles/addons/slurm/readme.rst
  roles/addons/slurm/tasks/main.yml
  roles/addons/slurm/templates/slurm.conf.j2
  roles/addons/slurm/vars/RedHat.yml
  roles/addons/slurm/vars/Ubuntu.yml
Labels: backport, documentation

#371 Backport/1.3/368
  roles/core/repositories_client/molecule/default/molecule.yml
  roles/core/repositories_client/molecule/default/prepare.yml
  roles/core/repositories_client/molecule/default/verify.yml
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
Labels: backport, bug

#372 Fix: documentation - prometheus
  resources/documentation/monitoring/prometheus.rst
Labels: bug, documentation

#376 backport: add firewall to prometheus (#361)
  roles/addons/prometheus_client/tasks/main.yml
  roles/addons/prometheus_server/files/alertmanager.xml
  roles/addons/prometheus_server/handlers/main.yml
  roles/addons/prometheus_server/tasks/main.yml
Labels: backport

#378 fix: don't create ini file if absent
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
Labels: bug, ci/cd, needs-backport

#379 fix: force to enter integer in select_from_list()
  roles/addons/diskless/files/disklessset.py
Labels: bug, needs-backport

#380 fix: umount diskless image when workdir exists
  roles/addons/diskless/files/disklessset.py
Labels: bug, needs-backport

#381 fix: check if diskless image_metadata.yml exists
  roles/addons/diskless/files/disklessset.py
Labels: bug, needs-backport

#377 backport: adding example and clarification (#357)
  roles/addons/diskless/files/disklessset.py
  roles/addons/diskless/readme.rst
Labels: backport

#383 fix: backports for disklessset (#379 #380 #381)
  roles/addons/diskless/files/disklessset.py
Labels: backport, bug

#382 fix: don't create ini file if absent
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
Labels: backport, bug, ci/cd

#387 doc: rephrase and fix the CHANGELOG
  CHANGELOG.md
  resources/documentation/deploy_bluebanquise.rst
Labels: documentation, needs-backport

#388 fix: ensure ep_ipxe_embed is defined before use
  roles/addons/report/templates/equipment_profiles.html.j2
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: bug

#392 fix: ensure ep_ipxe_embed is defined before use
  roles/addons/report/templates/equipment_profiles.html.j2
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: backport, bug

#391 doc: rephrase and fix the CHANGELOG and doc
  CHANGELOG.md
  resources/documentation/deploy_bluebanquise.rst
Labels: backport

#389 Fix: pxe_stack - add grub2 shell in menu.ipxe
  roles/core/pxe_stack/templates/menu.ipxe.j2
Labels: bug

#390 Feat: Add Lmod role
  CHANGELOG.md
  resources/packaging/bluebanquise.spec
  roles/addons/Lmod/readme.rst
  roles/addons/Lmod/tasks/main.yml
  roles/addons/Lmod/templates/modules_extra_path.sh.j2
  roles/addons/Lmod/vars/RedHat.yml
Labels: enhancement

#394 fix: missing packages in conman role
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/openldap_server/vars/RedHat_7.yml
  roles/addons/openldap_server/vars/RedHat_8.yml
  roles/addons/openldap_server/vars/main.yml
  roles/core/conman/molecule/default/prepare.yml
  roles/core/conman/tasks/main.yml
  roles/core/conman/vars/RedHat_7.yml
  roles/core/conman/vars/RedHat_8.yml
  roles/core/conman/vars/main.yml
  roles/core/nfs_client/vars/RedHat_7.yml
  roles/core/nfs_client/vars/RedHat_8.yml
Labels: bug, needs-backport
