Repository bluebanquise/bluebanquise, pull requests merged in 2020-04, with the labels that each got.

#143 Fix: Adding missing role Ansible
  roles/core/ansible/readme.rst
  roles/core/ansible/tasks/main.yml
Labels: bug

#148 fix: update specfile to build the RPM
  bluebanquise.spec
Labels: needs-backport

#155 feat: Use Python's logging with bootset
  roles/core/pxe_stack/files/bootset.py
Labels: enhancement

#156 [advanced_dhcp_sever] remove references to ntp_ip variable (#153)
  resources/documentation/configure_bluebanquise.rst
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice1-1.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice2-1.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice3-1.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/networks/ice3-2.yml
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2
Labels: backport

#159 feat: tune NM_CONTROLLED in nic role
  roles/core/nic/defaults/main.yml
  roles/core/nic/tasks/main.yml.old
  roles/core/nic/templates/ifcfg.j2
Labels: enhancement

#161 Backport repositories configuration
  inventory/group_vars/all/general_settings/external.yml
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
Labels: backport, invalid

#162 ci: introduce unit testing of roles with Molecule
  .travis.yml
  roles/core/dns_server/.ansible-lint
  roles/core/dns_server/.yamllint
  roles/core/dns_server/molecule/default/INSTALL.rst
  roles/core/dns_server/molecule/default/converge.yml
  roles/core/dns_server/molecule/default/molecule.yml
  roles/core/dns_server/molecule/default/prepare.yml
  roles/core/dns_server/molecule/default/verify.yml
  roles/core/dns_server/tasks/main.yml
  roles/core/dns_server/vars/main.yml
  roles/core/time/.ansible-lint
  roles/core/time/.yamllint
  roles/core/time/molecule/default/INSTALL.rst
  roles/core/time/molecule/default/converge.yml
  roles/core/time/molecule/default/molecule.yml
  roles/core/time/molecule/default/prepare.yml
  roles/core/time/molecule/default/verify.yml
  roles/core/time/vars/main.yml
Labels: enhancement

#157 docs: add backports section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#154 feat: security.ssh.hostkey_checking=true|false
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/security.yml
  resources/examples/simple_cluster/inventory/group_vars/all/security.yml
  roles/core/ssh_master/readme.rst
  roles/core/ssh_master/templates/config.j2
Labels: enhancement

#180 Fix: Adding advanced development guidelines.
  CONTRIBUTING.md
Labels: documentation

#160 docs: configure SSH public key before OS deployment
  resources/documentation/deploy_bluebanquise.rst
Labels: documentation

#158 fix: improve DNS forward and reverse templates
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml
  resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml
  roles/core/dns_server/templates/forward.j2
  roles/core/dns_server/templates/reverse.j2
Labels: bug, needs-backport

#184 Fix: improve Ansible documentation
  resources/documentation/learn_ansible.rst
Labels: documentation

#188 Fix: conman template issue
  roles/core/conman/templates/conman.conf.j2
Labels: bug

#193 Fix NFS inventories description
  inventory/group_vars/all/general_settings/nfs.yml
  resources/examples/simple_cluster/group_vars/all/general_settings/nfs.yml
Labels: backport

#190 fix: improve DNS forward and reverse templates (#158)
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/external.yml
  resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml
  roles/core/dns_server/templates/forward.j2
  roles/core/dns_server/templates/reverse.j2
Labels: backport

#194 Fix network generation with bonding
  roles/core/nic/tasks/main.yml
Labels: bug

#170 ci: molecule unit test for conman
  .github/workflows/molecule-actions.yml
  roles/core/conman/.yamllint
  roles/core/conman/molecule/default/INSTALL.rst
  roles/core/conman/molecule/default/converge.yml
  roles/core/conman/molecule/default/molecule.yml
  roles/core/conman/molecule/default/prepare.yml
Labels: ci/cd

#171 ci: molecule unit test for repositories_client
  .github/workflows/molecule-actions.yml
  roles/core/repositories_client/.yamllint
  roles/core/repositories_client/molecule/default/INSTALL.rst
  roles/core/repositories_client/molecule/default/converge.yml
  roles/core/repositories_client/molecule/default/molecule.yml
Labels: ci/cd

#197 fix: role time need tzdata for Ubuntu
  roles/core/time/vars/main.yml
Labels: bug

#196 fix: correct loop in dns_server handlers
  roles/core/dns_server/handlers/main.yml
  roles/core/dns_server/tasks/main.yml
Labels: bug

#149 Use repo variables in repositories_client
  resources/documentation/install_first_management.rst
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  roles/core/pxe_stack/files/osdeploy/centos_7.ipxe
  roles/core/pxe_stack/files/osdeploy/centos_8.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe
  roles/core/pxe_stack/templates/configuration_centos.ipxe.j2
  roles/core/pxe_stack/templates/equipment_profile.ipxe.j2
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/opensuse_leap_15.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
  roles/core/repositories_client/templates/releasever.j2
  roles/core/repositories_client/vars/main.yml
  roles/core/repositories_server/readme.rst
Labels: breaking change, enhancement

#199 feat: default to major distro for pxe boot images
  resources/documentation/install_first_management.rst
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_SMP/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_compute/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_supermicro_sandy_login/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeC/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeL/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeM/equipment_profile.yml
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/templates/equipment_profile.ipxe.j2
  roles/core/pxe_stack/vars/main.yml
Labels: enhancement

#200 feat: add optional param repositories_environment
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/all/all_equipments/equipment_profile.yml
  roles/core/pxe_stack/files/osdeploy/centos_7.ipxe
  roles/core/pxe_stack/files/osdeploy/centos_8.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe
  roles/core/pxe_stack/templates/equipment_profile.ipxe.j2
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
  roles/core/repositories_client/templates/environment.j2
Labels: enhancement
