Repository bluebanquise/bluebanquise, pull requests merged in 2020-12, with the labels that each got.

#499 feat: ensure firewalld zones exist
  roles/core/firewall/handlers/main.yml
  roles/core/firewall/readme.rst
  roles/core/firewall/tasks/RedHat.yml
  roles/core/firewall/vars/main.yml
Labels: enhancement

#498 feat: add configuration of firewall zone to nic
  roles/core/nic/readme.rst
  roles/core/nic/templates/ifcfg.j2
  roles/core/nic/vars/main.yml
Labels: enhancement

#506 fix: skip ansible-lint rule 208 when recurse: yes
  roles/core/conman/tasks/main.yml
  roles/core/log_server/tasks/main.yml
Labels: bug, needs-backport

#505 bug fix: missing setting of current_hostvars
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
Labels: bug
