Repository bluebanquise/bluebanquise, pull requests merged in 2020-07, with the labels that each got.

#260 Feat: Add powerman role
  bluebanquise.spec
  roles/addons/powerman/handlers/main.yml
  roles/addons/powerman/readme.rst
  roles/addons/powerman/tasks/main.yml
  roles/addons/powerman/templates/powerman.conf.j2
  roles/addons/powerman/vars/main.yml
Labels: enhancement

#270 feat: deprecate external_repositories
  roles/core/repositories_client/molecule/default/molecule.yml
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/deprecation.yml
  roles/core/repositories_client/tasks/main.yml
  roles/core/repositories_client/vars/main.yml
Labels: enhancement

#272 fix: make converter compatible with older PyYAML
  tools/inventory-converter-1.3-network_interfaces.py
Labels: bug

#255 feat: add role core/firewall
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-firewall.yml
  roles/core/firewall/.yamllint
  roles/core/firewall/molecule/default/INSTALL.rst
  roles/core/firewall/molecule/default/converge.yml
  roles/core/firewall/molecule/default/molecule.yml
  roles/core/firewall/molecule/default/verify.yml
  roles/core/firewall/readme.rst
  roles/core/firewall/tasks/RedHat.yml
  roles/core/firewall/tasks/main.yml
  roles/core/firewall/vars/RedHat.yml
  roles/core/firewall/vars/main.yml
Labels: enhancement

#281 Fix: Update advanced dhcp server to new nic syntax
  roles/advanced-core/advanced_dhcp_server/readme.rst
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.conf.j2
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.networks.conf.j2
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
  roles/advanced-core/advanced_dhcp_server/vars/main.yml
Labels: bug, enhancement

#286 feat: addon/root_password
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-addons-root_password.yml
  bluebanquise.spec
  roles/addons/root_password/.yamllint
  roles/addons/root_password/molecule/default/INSTALL.rst
  roles/addons/root_password/molecule/default/converge.yml
  roles/addons/root_password/molecule/default/molecule.yml
  roles/addons/root_password/molecule/default/password_hash
  roles/addons/root_password/molecule/default/verify.yml
  roles/addons/root_password/readme.rst
  roles/addons/root_password/tasks/main.yml
Labels: enhancement

#291 Fix ssh master template
  roles/core/ssh_master/templates/config.j2
Labels: bug

#290 Fix: bug in hosts_file template
  roles/core/hosts_file/templates/hosts.j2
Labels: bug

#295 fix: build RPM for addon sssd
  resources/packaging/bluebanquise.spec
Labels: bug

#293 fix: define baseurl_prefix as single line value
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
Labels: bug

#297 fix selinux context in log_server and conman roles
  roles/core/conman/tasks/main.yml
  roles/core/log_server/tasks/main.yml
Labels: bug
