Repository bluebanquise/bluebanquise, pull requests merged in 2020-11, with the labels that each got.

#458 feat: add parameter state to repositories_client
  roles/core/repositories_client/molecule/default/molecule.yml
  roles/core/repositories_client/molecule/default/prepare.yml
  roles/core/repositories_client/molecule/default/verify.yml
  roles/core/repositories_client/readme.rst
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/opensuse_leap_15.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
  roles/core/repositories_client/tasks/ubuntu_18.yml
  roles/core/repositories_client/vars/main.yml
Labels: enhancement

#412 Add molecule tests for nfs_server and nfs_client
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-nfs_client.yml
  .github/workflows/molecule-actions-core-nfs_server.yml
  roles/core/nfs_client/.yamllint
  roles/core/nfs_client/defaults/main.yml
  roles/core/nfs_client/molecule/default/INSTALL.rst
  roles/core/nfs_client/molecule/default/converge.yml
  roles/core/nfs_client/molecule/default/molecule.yml
  roles/core/nfs_client/molecule/default/verify.yml
  roles/core/nfs_client/readme.rst
  roles/core/nfs_client/tasks/main.yml
  roles/core/nfs_client/vars/main.yml
  roles/core/nfs_server/.yamllint
  roles/core/nfs_server/molecule/default/INSTALL.rst
  roles/core/nfs_server/molecule/default/converge.yml
  roles/core/nfs_server/molecule/default/molecule.yml
  roles/core/nfs_server/molecule/default/prepare.yml
  roles/core/nfs_server/molecule/default/verify.yml
  roles/core/nfs_server/readme.rst
  roles/core/nfs_server/vars/main.yml
Labels: ci/cd

#440 Fix: doc - update multiple icebergs documentation
  resources/documentation/images/multiple_icebergs_1.svg
  resources/documentation/images/multiple_icebergs_2.svg
  resources/documentation/images/multiple_icebergs_3.svg
  resources/documentation/images/multiple_icebergs_4.svg
  resources/documentation/images/multiple_icebergs_5.svg
  resources/documentation/images/multiple_icebergs_6.svg
  resources/documentation/images/multiple_icebergs_7.svg
  resources/documentation/images/multiple_icebergs_j2.svg
  resources/documentation/multiple_icebergs.rst
Labels: documentation

#413 Add unitary molecule tests for dhcp_server role
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-dhcp_server.yml
  roles/core/dhcp_server/.yamllint
  roles/core/dhcp_server/molecule/default/INSTALL.rst
  roles/core/dhcp_server/molecule/default/converge.yml
  roles/core/dhcp_server/molecule/default/molecule.yml
  roles/core/dhcp_server/molecule/default/prepare.yml
  roles/core/dhcp_server/molecule/default/verify.yml
Labels: ci/cd

#454 Oxedions/quality
  resources/documentation/roles.rst
  resources/packaging/bluebanquise.spec
  roles/addons/clone/readme.rst
  roles/addons/clone/vars/main.yml
  roles/addons/clustershell/vars/main.yml
  roles/addons/diskless/vars/main.yml
  roles/addons/grafana/vars/main.yml
  roles/addons/lmod/vars/main.yml
  roles/addons/nic_nmcli/vars/main.yml
  roles/addons/ofed/vars/main.yml
  roles/addons/ofed_sm/vars/main.yml
  roles/addons/openldap_client/vars/main.yml
  roles/addons/openldap_server/vars/main.yml
  roles/addons/prometheus_client/vars/main.yml
  roles/addons/prometheus_server/vars/main.yml
  roles/addons/report/vars/main.yml
  roles/addons/root_password/readme.rst
  roles/addons/root_password/vars/main.yml
  roles/addons/singularity/README.md
  roles/addons/singularity/readme.rst
  roles/addons/singularity/vars/main.yml
  roles/addons/slurm/vars/main.yml
  roles/addons/sssd/vars/main.yml
  roles/addons/users_basic/vars/main.yml
  roles/core/access_control/vars/main.yml
  roles/core/display_tuning/vars/main.yml
  roles/core/hosts_file/vars/main.yml
  roles/core/log_client/vars/main.yml
  roles/core/log_server/vars/main.yml
  roles/core/nic/vars/main.yml
  roles/core/pxe_stack/vars/main.yml
  roles/core/ssh_master/vars/main.yml
  roles/macros/README
  roles/macros/accelerated.j2
  roles/macros/network.j2
Labels: bug, documentation, enhancement

#428 Adding molecule unitary tests for advanced_dhcp_server role
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-advanced-core-advanced_dhcp_server.yml
  roles/advanced-core/advanced_dhcp_server/.yamllint
  roles/advanced-core/advanced_dhcp_server/molecule/default/INSTALL.rst
  roles/advanced-core/advanced_dhcp_server/molecule/default/converge.yml
  roles/advanced-core/advanced_dhcp_server/molecule/default/molecule.yml
  roles/advanced-core/advanced_dhcp_server/molecule/default/prepare.yml
  roles/advanced-core/advanced_dhcp_server/molecule/default/verify.yml
Labels: ci/cd

#439 Adding unitary molecule tests for pxe_stack role
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-pxe_stack.yml
  roles/core/pxe_stack/.yamllint
  roles/core/pxe_stack/molecule/default/INSTALL.rst
  roles/core/pxe_stack/molecule/default/converge.yml
  roles/core/pxe_stack/molecule/default/molecule.yml
  roles/core/pxe_stack/molecule/default/prepare.yml
  roles/core/pxe_stack/molecule/default/verify.yml
Labels: ci/cd

#461 Fix: core/display_tuning - Remove dynamic elements
  roles/core/display_tuning/files/screenrc
Labels: bug

#462 Add molecule tests for repositories_server and ssh_slave roles
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-repositories_server.yml
  .github/workflows/molecule-actions-core-ssh_slave.yml
  roles/core/repositories_server/.yamllint
  roles/core/repositories_server/molecule/default/INSTALL.rst
  roles/core/repositories_server/molecule/default/converge.yml
  roles/core/repositories_server/molecule/default/molecule.yml
  roles/core/repositories_server/molecule/default/prepare.yml
  roles/core/repositories_server/molecule/default/verify.yml
  roles/core/ssh_slave/.yamllint
  roles/core/ssh_slave/molecule/default/INSTALL.rst
  roles/core/ssh_slave/molecule/default/converge.yml
  roles/core/ssh_slave/molecule/default/molecule.yml
  roles/core/ssh_slave/molecule/default/verify.yml
Labels: ci/cd

#444 Feat: addons/nic_nmcli - Add all options
  CHANGELOG.md
  roles/addons/nic_nmcli/defaults/main.yml
  roles/addons/nic_nmcli/handlers/main.yml
  roles/addons/nic_nmcli/readme.rst
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/nic_nmcli/vars/main.yml
Labels: breaking change, enhancement, help wanted

#448 Feat: addons/nhc
  CHANGELOG.md
  resources/documentation/roles.rst
  resources/packaging/bluebanquise.spec
  roles/addons/nhc/defaults/main.yml
  roles/addons/nhc/readme.rst
  roles/addons/nhc/tasks/main.yml
  roles/addons/nhc/templates/nhc.conf.j2
  roles/addons/nhc/vars/RedHat.yml
  roles/addons/nhc/vars/main.yml
Labels: enhancement

#472 Fix: doc - Add global MI schema (missing)
  resources/documentation/images/multiple_icebergs_1bis.svg
  resources/documentation/multiple_icebergs.rst
Labels: bug, documentation

#480 Backport/1.3/394
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/openldap_server/vars/RedHat_7.yml
  roles/addons/openldap_server/vars/RedHat_8.yml
  roles/addons/openldap_server/vars/main.yml
  roles/core/conman/molecule/default/prepare.yml
  roles/core/conman/tasks/main.yml
  roles/core/conman/vars/RedHat_7.yml
  roles/core/conman/vars/RedHat_8.yml
  roles/core/conman/vars/main.yml
  roles/core/nfs_client/vars/RedHat_7.yml
  roles/core/nfs_client/vars/RedHat_8.yml
Labels: backport

#478 Fix: core/dns_server - Missing bmc alias
  roles/core/dns_server/templates/forward.j2
Labels: backport, bug

#477 Fix: adv_core/adv_dns_server
  roles/advanced-core/advanced_dns_server/templates/forward.j2
Labels: backport, bug

#476 fix: ensure selinux type is correct on diskless directories
  roles/addons/diskless/tasks/main.yml
Labels: backport

#475 Backport/1.3/406
  roles/core/hosts_file/templates/hosts.j2
Labels: backport

#483 Fix: core/nfs_client - Bad condition
  roles/core/nfs_client/tasks/main.yml
Labels: bug, needs-backport

#485 Fix: core/nfs_client - Bad condition (#483)
  roles/core/nfs_client/tasks/main.yml
Labels: backport

#481 Feat: addons/kernel_config - role creation
  CHANGELOG.md
  resources/packaging/bluebanquise.spec
  roles/addons/kernel_config/defaults/main.yml
  roles/addons/kernel_config/readme.rst
  roles/addons/kernel_config/tasks/main.yml
  roles/addons/kernel_config/vars/main.yml
Labels: enhancement

#469 Feat: addons/nic_nmcli - Merge routes task into nic_nmcli
  CHANGELOG.md
  roles/addons/nic_nmcli/readme.rst
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/nic_nmcli/vars/main.yml
Labels: enhancement

#463 Conman : Improve molecule tests
  roles/core/conman/molecule/default/prepare.yml
  roles/core/conman/molecule/default/verify.yml
Labels: ci/cd

#434 fix: execute the gather variables task even with specific tags
  .github/workflows/static_analysis.yml
  roles/addons/diskless/tasks/main.yml
  roles/addons/grafana/tasks/main.yml
  roles/addons/lmod/tasks/main.yml
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/singularity/tasks/main.yml
  roles/addons/slurm/tasks/main.yml
  roles/advanced-core/advanced_dhcp_server/tasks/main.yml
  roles/advanced-core/advanced_dns_server/tasks/main.yml
  roles/core/bluebanquise/tasks/main.yml
  roles/core/conman/tasks/main.yml
  roles/core/dhcp_server/tasks/main.yml
  roles/core/dns_server/tasks/main.yml
  roles/core/firewall/tasks/main.yml
  roles/core/log_client/tasks/main.yml
  roles/core/log_server/tasks/main.yml
  roles/core/nfs_client/tasks/main.yml
  roles/core/nfs_server/tasks/main.yml
  roles/core/pxe_stack/tasks/Ubuntu_18.yml
  roles/core/pxe_stack/tasks/main.yml
  roles/core/repositories_server/tasks/main.yml
  roles/core/time/tasks/main.yml
  tools/gather_vars_checker.py
Labels: bug, needs-backport

#487 Feat: podman - Create Dockerfile
  resources/podman/Dockerfile
  resources/podman/README.md
Labels: enhancement

#490 fix: execute the gather variables task even with specific tags
  .github/workflows/static_analysis.yml
  roles/addons/diskless/tasks/main.yml
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/slurm/tasks/main.yml
  roles/advanced-core/advanced_dhcp_server/tasks/main.yml
  roles/advanced-core/advanced_dns_server/tasks/main.yml
  roles/core/bluebanquise/tasks/main.yml
  roles/core/conman/tasks/main.yml
  roles/core/dhcp_server/tasks/main.yml
  roles/core/dns_server/tasks/main.yml
  roles/core/firewall/tasks/main.yml
  roles/core/log_client/tasks/main.yml
  roles/core/log_server/tasks/main.yml
  roles/core/nfs_client/tasks/main.yml
  roles/core/nfs_server/tasks/main.yml
  roles/core/pxe_stack/tasks/Ubuntu_18.yml
  roles/core/pxe_stack/tasks/main.yml
  roles/core/repositories_server/tasks/main.yml
  roles/core/time/tasks/main.yml
  tools/gather_vars_checker.py
Labels: backport

#470 Feat: adv_core/adv_dhcp_server - Add multiple features
  CHANGELOG.md
  roles/advanced-core/advanced_dhcp_server/defaults/main.yml
  roles/advanced-core/advanced_dhcp_server/molecule/default/molecule.yml
  roles/advanced-core/advanced_dhcp_server/readme.rst
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.conf.j2
  roles/advanced-core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
  roles/advanced-core/advanced_dhcp_server/vars/main.yml
Labels: enhancement

#497 feat: template custom NHC files from the inventory
  roles/addons/nhc/defaults/main.yml
  roles/addons/nhc/readme.rst
  roles/addons/nhc/tasks/main.yml
  roles/addons/nhc/templates/nhc.conf.j2
  roles/addons/nhc/templates/nhc_custom_file.j2
  roles/addons/nhc/vars/main.yml
Labels: enhancement
