Repository bluebanquise/bluebanquise, pull requests merged in 2020-01, with the labels that each got.

#64 Update main.yml
  roles/addons/ofed/tasks/main.yml
Labels: bug

#65 Update main.yml
  roles/addons/ofed_sm/tasks/main.yml
Labels: bug

#56 config: use /etc/bluebanquise as default directory
  .gitignore
  ansible.cfg
  resources/documentation/configure_bluebanquise.rst
  resources/documentation/deploy_bluebanquise.rst
  resources/documentation/vocabulary.rst
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/nfs.yml
  resources/tools/bluebanquise_accelerated_mode
  roles/addons/users_basic/readme.rst
  roles/core/hosts_file/readme.rst
  roles/core/repositories_server/readme.rst
  roles/core/ssh_slave/readme.rst
  roles/core/time/readme.rst
Labels: enhancement

#83 style: make static code analysis happy
  roles/addons/prometheus_client/files/nhc_exporter.py
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
  roles/core/repositories_client/tasks/redhat_7.yml
  roles/core/repositories_client/tasks/redhat_8.yml
Labels: bug

#88 feat: Disable CentOS distro repositories
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/general_settings/repositories.yml
  resources/examples/simple_cluster/inventory/group_vars/all/general_settings/repositories.yml
  roles/core/repositories_client/handlers/main.yml
  roles/core/repositories_client/tasks/centos_7.yml
  roles/core/repositories_client/tasks/centos_8.yml
Labels: bug, enhancement

#87 fix: comment external_repositories
  resources/examples/simple_cluster/inventory/group_vars/all/general_settings/external.yml
Labels: bug

#90 fix: debug diskless role
  roles/addons/diskless/files/disklessset.py
  roles/addons/diskless/tasks/main.yml
Labels: bug

#92 fix: [pxe_stack] remove recursive setting of perms
  roles/core/pxe_stack/tasks/main.yml
Labels: bug
