Repository bluebanquise/bluebanquise, pull requests merged in 2020-08, with the labels that each got.

#304 fix: correct markdown rendering in GitHub
  roles/core/pxe_stack/readme.rst
Labels: documentation

#301 Enhance disklessset livenet
  roles/addons/diskless/files/disklessset.py
  roles/addons/diskless/readme.rst
  roles/addons/diskless/tasks/main.yml
Labels: bug, enhancement

#294 ci: trigger Test RPM build for pull request
  .github/workflows/rpmbuild-action.yml
Labels: ci/cd

#298 ci: remove ubuntu tests
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-addons-clustershell.yml
  .github/workflows/molecule-actions-addons-root_password.yml
  .github/workflows/molecule-actions-addons-users_basic.yml
  .github/workflows/molecule-actions-core-conman.yml
  .github/workflows/molecule-actions-core-display_tuning.yml
  .github/workflows/molecule-actions-core-dns_client.yml
  .github/workflows/molecule-actions-core-dns_server.yml
  .github/workflows/molecule-actions-core-log_client.yml
  .github/workflows/molecule-actions-core-ssh_master.yml
  .github/workflows/molecule-actions-core-time.yml
Labels: ci/cd

#306 Call imgstat in ipxe files to get image report
  roles/addons/diskless/files/disklessset.py
  roles/core/pxe_stack/files/osdeploy/centos_7.ipxe
  roles/core/pxe_stack/files/osdeploy/centos_8.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe
Labels: enhancement

#310 fix: create a per-image diskless working dir
  roles/addons/diskless/files/disklessset.py
Labels: enhancement

#315 feat: display kickstart file of node with bootset
  roles/core/pxe_stack/files/bootset.py
Labels: enhancement

#314 fix: group bootset status per boot type and image
  roles/core/pxe_stack/files/bootset.py
Labels: enhancement

#313 fix: diskless metadata
  roles/addons/diskless/files/disklessset.py
Labels: breaking change

#316 ci: do not install ansible 2.9.12
  .github/workflows/molecule-actions-addons-clustershell.yml
  .github/workflows/molecule-actions-addons-root_password.yml
  .github/workflows/molecule-actions-addons-users_basic.yml
  .github/workflows/molecule-actions-core-bluebanquise.yml
  .github/workflows/molecule-actions-core-conman.yml
  .github/workflows/molecule-actions-core-display_tuning.yml
  .github/workflows/molecule-actions-core-dns_client.yml
  .github/workflows/molecule-actions-core-dns_server.yml
  .github/workflows/molecule-actions-core-firewall.yml
  .github/workflows/molecule-actions-core-log_client.yml
  .github/workflows/molecule-actions-core-log_server.yml
  .github/workflows/molecule-actions-core-repositories_client.yml
  .github/workflows/molecule-actions-core-ssh_master.yml
  .github/workflows/molecule-actions-core-time.yml
  .github/workflows/static_analysis.yml
Labels: ci/cd

#318 Fix: small issue in nfs_client role packages list
  roles/core/nfs_client/vars/RedHat.yml
  roles/core/nfs_client/vars/Ubuntu.yml
Labels: bug

#319 Fix: Add yum to livenet image type 2
  roles/addons/diskless/files/disklessset.py
Labels: bug

#320 doc: replace all_equipment with equipment_all
  CONTRIBUTING.md
  roles/core/ssh_slave/readme.rst
Labels: documentation

#323 Fix: Missing code blocks in repositories_client role
  roles/core/repositories_client/readme.rst
Labels: bug

#322 Fix: Add missing karma service and configuration
  roles/addons/prometheus_server/defaults/main.yml
  roles/addons/prometheus_server/tasks/main.yml
  roles/addons/prometheus_server/templates/karma.yml.j2
Labels: bug

#331 fix: drop macro node_main_nic from pxe_stack
  roles/core/pxe_stack/templates/nodes_parameters.yml.j2
Labels: bug

#336 fix: typo in role advanced_dns_server
  roles/advanced-core/advanced_dns_server/handlers/main.yml
  roles/advanced-core/advanced_dns_server/tasks/main.yml
Labels: bug

#338 oxedions/fix/repositories_client_readme
  roles/core/repositories_client/readme.rst
Labels: bug, documentation

#337 fix: typo in template slurm.conf.j2, list of packages and chmod 0755 slurm config dir
  roles/addons/slurm/tasks/main.yml
  roles/addons/slurm/templates/slurm.conf.j2
Labels: bug

#343 Fix: Update inventory examples
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/equipment_all/authentication.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/all/equipment_all/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_typeC/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_typeL/equipment_profile.yml
  resources/examples/multi_icebergs_cluster/inventory/group_vars/equipment_typeM/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/all/equipment_all/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeC/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeG/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeL/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeM/equipment_profile.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeM/monitoring.yml
  resources/examples/simple_cluster/inventory/group_vars/equipment_typeS/equipment_profile.yml
Labels: bug, documentation

#345 fix: use '>' instead of 'gt' in j2 templates
  roles/core/time/templates/chrony.conf.j2
Labels: bug

#352 fix: stop firewall service if ep_firewall = False
  roles/core/firewall/tasks/main.yml
Labels: bug

#353 fix: update bluebanquise.spec for 1.3
  resources/packaging/bluebanquise.spec
Labels: bug

#350 fix: enable SELinux daemons_use_tty for conman
  roles/core/conman/tasks/main.yml
Labels: bug

#339 Fix/oxedions/documentation update
  resources/documentation/configure_bluebanquise.rst
  resources/documentation/containers.rst
  resources/documentation/deploy_bluebanquise.rst
  resources/documentation/index.rst
  resources/documentation/learn_ansible.rst
  resources/documentation/multiple_icebergs.rst
  resources/documentation/stories.rst
Labels: documentation

#330 Feat/monitoring documentation
  resources/documentation/conf.py
  resources/documentation/monitoring.rst
  resources/documentation/monitoring/capture/grafana/BarGaugeex1.PNG
  resources/documentation/monitoring/capture/grafana/BarGaugeex2.PNG
  resources/documentation/monitoring/capture/grafana/BarGaugeex3.PNG
  resources/documentation/monitoring/capture/grafana/Capture.PNG
  resources/documentation/monitoring/capture/grafana/Captureshow.PNG
  resources/documentation/monitoring/capture/grafana/LegendExample.PNG
  resources/documentation/monitoring/capture/grafana/MainDashboard.PNG
  resources/documentation/monitoring/capture/grafana/ValueMappingEx.PNG
  resources/documentation/monitoring/capture/grafana/Variable1.PNG
  resources/documentation/monitoring/capture/grafana/createDashboard1.PNG
  resources/documentation/monitoring/capture/grafana/createDashboard2.PNG
  resources/documentation/monitoring/capture/grafana/createDashboard3.PNG
  resources/documentation/monitoring/capture/grafana/legend_field1.PNG
  resources/documentation/monitoring/capture/grafana/legend_field2.PNG
  resources/documentation/monitoring/capture/grafana/mainDashboard2.PNG
  resources/documentation/monitoring/capture/grafana/supp1.PNG
  resources/documentation/monitoring/capture/grafana/supp2.PNG
  resources/documentation/monitoring/capture/grafana/supp3.PNG
  resources/documentation/monitoring/capture/grafana/thresholdExample1.PNG
  resources/documentation/monitoring/capture/grafana/thresholdExample2.PNG
  resources/documentation/monitoring/capture/grafana/transform1.PNG
  resources/documentation/monitoring/capture/grafana/transformExample.PNG
  resources/documentation/monitoring/capture/grafana/transformExample2.PNG
  resources/documentation/monitoring/capture/grafana/transformExample3.PNG
  resources/documentation/monitoring/capture/grafana/variable.PNG
  resources/documentation/monitoring/capture/grafana/variable2.PNG
  resources/documentation/monitoring/capture/grafana/variable3.PNG
  resources/documentation/monitoring/capture/grafana/variable4.PNG
  resources/documentation/monitoring/capture/prometheus/query1.PNG
  resources/documentation/monitoring/capture/prometheus/query2.PNG
  resources/documentation/monitoring/capture/prometheus/query3.PNG
  resources/documentation/monitoring/capture/prometheus/query4.PNG
  resources/documentation/monitoring/capture/prometheus/query5.PNG
  resources/documentation/monitoring/capture/prometheus/query6.PNG
  resources/documentation/monitoring/capture/prometheus/query7.PNG
  resources/documentation/monitoring/capture/prometheus/query8.PNG
  resources/documentation/monitoring/capture/prometheus/query9.PNG
  resources/documentation/monitoring/exporter.rst
  resources/documentation/monitoring/grafana.rst
  resources/documentation/monitoring/ha_cluster_exporter.rst
  resources/documentation/monitoring/introduction.rst
  resources/documentation/monitoring/ipmi_exporter.rst
  resources/documentation/monitoring/node_exporter.rst
  resources/documentation/monitoring/prometheus.rst
  resources/documentation/monitoring/slurm_exporter.rst
  resources/documentation/monitoring/snmp_exporter.rst
  resources/documentation/roles.rst
  roles/addons/prometheus_client/defaults/main.yml
  roles/addons/prometheus_client/readme.rst
  roles/addons/prometheus_server/defaults/main.yml
  roles/addons/prometheus_server/readme.rst
  roles/core/dhcp_server/readme.rst
  roles/core/pxe_stack/readme.rst
Labels: documentation

#317 Revert "ci: do not install ansible 2.9.12"
  .github/workflows/molecule-actions-addons-clustershell.yml
  .github/workflows/molecule-actions-addons-root_password.yml
  .github/workflows/molecule-actions-addons-users_basic.yml
  .github/workflows/molecule-actions-core-bluebanquise.yml
  .github/workflows/molecule-actions-core-conman.yml
  .github/workflows/molecule-actions-core-display_tuning.yml
  .github/workflows/molecule-actions-core-dns_client.yml
  .github/workflows/molecule-actions-core-dns_server.yml
  .github/workflows/molecule-actions-core-firewall.yml
  .github/workflows/molecule-actions-core-log_client.yml
  .github/workflows/molecule-actions-core-log_server.yml
  .github/workflows/molecule-actions-core-repositories_client.yml
  .github/workflows/molecule-actions-core-ssh_master.yml
  .github/workflows/molecule-actions-core-time.yml
  .github/workflows/static_analysis.yml
Labels: bug, ci/cd
