Repository bluebanquise/bluebanquise, pull requests merged in 2021-12, with the labels that each got.

#638 Oxedions/ssh logs
  CHANGELOG.md
  roles/core/ssh_client/defaults/main.yml
  roles/core/ssh_client/molecule/default/molecule.yml
  roles/core/ssh_client/molecule/default/verify.yml
  roles/core/ssh_client/readme.rst
  roles/core/ssh_client/templates/config.j2
  roles/core/ssh_client/vars/main.yml
Labels: enhancement

#642 Fix: diskless - Update readme.rst regarding GPG keys
  roles/core/diskless/readme.rst
Labels: documentation

#648 Fix: bluebanquise - Add missing bluebanquise_filter package
  CHANGELOG.md
  roles/core/bluebanquise/readme.rst
  roles/core/bluebanquise/vars/RedHat.yml
  roles/core/bluebanquise/vars/RedHat_7.yml
  roles/core/bluebanquise/vars/Ubuntu.yml
  roles/core/bluebanquise/vars/Ubuntu_20.yml
  roles/core/bluebanquise/vars/main.yml
Labels: bug

#649 Fix: pxe_stack - Add bootset as package
  CHANGELOG.md
  roles/core/pxe_stack/files/bootset.py
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/tasks/main.yml
  roles/core/pxe_stack/vars/RedHat_7.yml
  roles/core/pxe_stack/vars/RedHat_8.yml
  roles/core/pxe_stack/vars/RedHat_9.yml
  roles/core/pxe_stack/vars/Ubuntu.yml
  roles/core/pxe_stack/vars/main.yml
Labels: bug, enhancement

#650 Fix: diskless - Remove script from role and rely on package
  CHANGELOG.md
  roles/core/diskless/readme.rst
  roles/core/diskless/tasks/main.yml
  roles/core/diskless/vars/RedHat_8.yml
  roles/core/diskless/vars/RedHat_9.yml
  roles/core/diskless/vars/main.yml
Labels: bug

#651 Fix: bluebanquise - Missing new line at end of YAML
  roles/core/bluebanquise/vars/RedHat.yml
  roles/core/bluebanquise/vars/Ubuntu.yml
  roles/core/bluebanquise/vars/Ubuntu_20.yml
Labels: bug

#652 Fix: pxe_stack - Fix bad rpm name introduced before
  roles/core/pxe_stack/vars/RedHat_7.yml
  roles/core/pxe_stack/vars/RedHat_8.yml
  roles/core/pxe_stack/vars/RedHat_9.yml
  roles/core/pxe_stack/vars/Ubuntu.yml
Labels: bug

#656 Fix: pxe_stack - Missing efi bootorder for ubuntu
  CHANGELOG.md
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/templates/Ubuntu/preseed.cfg.j2
  roles/core/pxe_stack/templates/Ubuntu/user-data.j2
  roles/core/pxe_stack/vars/main.yml
Labels: bug

#657 Fix: ssh_client - Issue with empty network interfaces
  CHANGELOG.md
  roles/core/ssh_client/readme.rst
  roles/core/ssh_client/templates/config.j2
  roles/core/ssh_client/vars/main.yml
Labels: bug

#640 Feat: conman - Add #639 related feature
  CHANGELOG.md
  resources/data_model.md
  roles/core/conman/readme.rst
  roles/core/conman/templates/conman.conf.j2
  roles/core/conman/vars/main.yml
  roles/core/powerman/readme.rst
  roles/core/powerman/templates/powerman.conf.j2
  roles/core/powerman/vars/main.yml
Labels: enhancement
