Repository bluebanquise/bluebanquise, pull requests merged in 2021-04, with the labels that each got.

#539 ci: fix ansible versions and failing tests
  .github/workflows/molecule-actions-core-time.yml
  .github/workflows/static_analysis.yml
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/powerman/tasks/main.yml
  roles/addons/prometheus_server/tasks/main.yml
  roles/advanced-core/advanced_dns_server/tasks/main.yml
  roles/core/conman/tasks/main.yml
  roles/core/dhcp_server/tasks/main.yml
  roles/core/dns_server/tasks/main.yml
  roles/core/firewall/tasks/RedHat.yml
  roles/core/log_client/tasks/main.yml
  roles/core/log_server/tasks/main.yml
  roles/core/nfs_server/tasks/main.yml
  roles/core/pxe_stack/tasks/main.yml
  roles/core/time/tasks/main.yml
  tox.ini
Labels: ci/cd

#546 Fix: log_server and client names
  roles/core/log_client/handlers/main.yml
  roles/core/log_client/tasks/main.yml
  roles/core/log_server/handlers/main.yml
  roles/core/log_server/readme.rst
  roles/core/log_server/tasks/main.yml
Labels: bug

#545 Feat: data_model - creation
  resources/data_model.md
Labels: documentation

#543 Feat: set_hostname - Add fqdn capability
  CHANGELOG.md
  roles/core/set_hostname/defaults/main.yml
  roles/core/set_hostname/molecule/default/converge.yml
  roles/core/set_hostname/readme.rst
  roles/core/set_hostname/tasks/main.yml
  roles/core/set_hostname/vars/main.yml
Labels: enhancement

#544 Fix: README - Update
  README.md
Labels: documentation

#535 fix: always run the gather OS variable tasks
  .github/workflows/static_analysis.yml
  roles/addons/diskless/tasks/main.yml
  roles/addons/grafana/tasks/main.yml
  roles/addons/lmod/tasks/main.yml
  roles/addons/nhc/tasks/main.yml
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/openldap_server/tasks/main.yml
  roles/addons/singularity/tasks/main.yml
  roles/addons/slurm/tasks/main.yml
  roles/advanced-core/advanced_dhcp_server/tasks/main.yml
  roles/advanced-core/advanced_dns_server/tasks/main.yml
  roles/core/bluebanquise/tasks/main.yml
  roles/core/conman/tasks/main.yml
  roles/core/dhcp_server/tasks/main.yml
  roles/core/dns_client/tasks/main.yml
  roles/core/dns_server/tasks/main.yml
  roles/core/firewall/tasks/main.yml
  roles/core/log_client/tasks/main.yml
  roles/core/log_server/tasks/main.yml
  roles/core/nfs_client/tasks/main.yml
  roles/core/nfs_server/tasks/main.yml
  roles/core/pxe_stack/tasks/main.yml
  roles/core/repositories_server/tasks/main.yml
  roles/core/time/tasks/main.yml
  tools/gather_vars_checker.py
Labels: bug

#550 fix: use tag package for package tasks
  roles/core/clustershell/tasks/main.yml
  roles/core/lvm/tasks/main.yml
  roles/core/powerman/tasks/main.yml
Labels: bug

#552 feat: set sysconfig OPTIONS for chronyd
  CHANGELOG.md
  roles/core/time/molecule/default/converge.yml
  roles/core/time/molecule/default/molecule.yml
  roles/core/time/molecule/default/verify.yml
  roles/core/time/readme.rst
  roles/core/time/tasks/main.yml
  roles/core/time/vars/main.yml
Labels: ci/cd, enhancement

#559 Fix: kernel_config - Prevent crash if variable is None
  roles/core/kernel_config/tasks/main.yml
Labels: bug
