Repository bluebanquise/bluebanquise, pull requests merged in 2021-11, with the labels that each got.

#628 Fix: all - Prevent random changed tasks status
  CHANGELOG.md
  roles/advanced_core/advanced_dhcp_server/readme.rst
  roles/advanced_core/advanced_dhcp_server/templates/dhcpd.subnet.conf.j2
  roles/advanced_core/advanced_dhcp_server/vars/main.yml
  roles/core/conman/readme.rst
  roles/core/conman/templates/conman.conf.j2
  roles/core/conman/vars/main.yml
  roles/core/dhcp_server/readme.rst
  roles/core/dhcp_server/templates/dhcpd.subnet.conf.j2
  roles/core/dhcp_server/vars/main.yml
  roles/core/hosts_file/readme.rst
  roles/core/hosts_file/templates/hosts.j2
  roles/core/hosts_file/vars/main.yml
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/templates/nodes_parameters.yml.j2
  roles/core/pxe_stack/vars/main.yml
  roles/core/ssh_master/readme.rst
  roles/core/ssh_master/templates/config.j2
  roles/core/ssh_master/vars/main.yml
Labels: bug

#632 Fix: Tox - Update envlist
  tox.ini
Labels: ci/cd

#605 Fix: conman - force conman user gid and uid
  .github/workflows/molecule-actions-core-conman.yml
  CHANGELOG.md
  roles/core/conman/defaults/main.yml
  roles/core/conman/readme.rst
  roles/core/conman/tasks/main.yml
  roles/core/conman/vars/main.yml
Labels: bug

#635 Fix: ssh_master ssh_slave - rename
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-ssh_client.yml
  .github/workflows/molecule-actions-core-ssh_remote_keys.yml
  CHANGELOG.md
  resources/examples/simple_cluster/playbooks/managements.yml
  roles/core/ssh_client/defaults/main.yml
  roles/core/ssh_client/molecule/default/INSTALL.rst
  roles/core/ssh_client/molecule/default/converge.yml
  roles/core/ssh_client/molecule/default/molecule.yml
  roles/core/ssh_client/molecule/default/prepare.yml
  roles/core/ssh_client/molecule/default/verify.yml
  roles/core/ssh_client/readme.rst
  roles/core/ssh_client/tasks/main.yml
  roles/core/ssh_client/templates/config.j2
  roles/core/ssh_client/vars/main.yml
  roles/core/ssh_master/vars/main.yml
  roles/core/ssh_remote_keys/molecule/default/INSTALL.rst
  roles/core/ssh_remote_keys/molecule/default/converge.yml
  roles/core/ssh_remote_keys/molecule/default/molecule.yml
  roles/core/ssh_remote_keys/molecule/default/verify.yml
  roles/core/ssh_remote_keys/readme.rst
  roles/core/ssh_remote_keys/tasks/main.yml
  roles/core/ssh_remote_keys/vars/main.yml
  roles/core/ssh_slave/molecule/default/converge.yml
  roles/core/ssh_slave/vars/main.yml
Labels: bug, breaking change

#629 Doc: Add more equipment_profiles
  resources/equipment_profiles/generic/nvidia_gpu.yml
  resources/equipment_profiles/generic/opensuse_leap_15.yml
  resources/equipment_profiles/generic/redhat_raid_by-path.yml
  resources/equipment_profiles/generic/ubuntu_18.yml
  resources/equipment_profiles/models/asus/Z10PA-U8.yml
  resources/equipment_profiles/models/dell/R610.yml
  resources/equipment_profiles/models/dell/R730.yml
  resources/equipment_profiles/models/fujistu/RX200_S8.yml
  resources/equipment_profiles/models/intel/HNS2600BPB.yml
  resources/equipment_profiles/models/supermicro/2028R-DE2CR24L.yml
  resources/equipment_profiles/models/supermicro/X9SRi-F.yml
Labels: documentation

#620 Feat: nfs_client - Change sebooleans input variables
  CHANGELOG.md
  roles/core/nfs_client/defaults/main.yml
  roles/core/nfs_client/readme.rst
  roles/core/nfs_client/tasks/main.yml
  roles/core/nfs_client/vars/main.yml
Labels: bug, enhancement

#633 Feat: pam_limits role creation
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-pam_limits.yml
  CHANGELOG.md
  roles/core/pam_limits/.yamllint
  roles/core/pam_limits/molecule/default/converge.yml
  roles/core/pam_limits/molecule/default/molecule.yml
  roles/core/pam_limits/molecule/default/prepare.yml
  roles/core/pam_limits/molecule/default/verify.yml
  roles/core/pam_limits/readme.rst
  roles/core/pam_limits/tasks/main.yml
  roles/core/pam_limits/vars/main.yml
Labels: enhancement
