Repository bluebanquise/bluebanquise, pull requests merged in 2021-01, with the labels that each got.

#492 RDMA requires higher lockable memory than the default. Memlock is set…
  CHANGELOG.md
  roles/addons/ofed/defaults/main.yml
  roles/addons/ofed/readme.rst
  roles/addons/ofed/tasks/main.yml
  roles/addons/ofed/vars/main.yml
Labels: enhancement

#511 ci: setup molecule for set_hostname
  .github/TEST_MATRIX.md
  .github/workflows/molecule-actions-core-set_hostname.yml
  roles/core/set_hostname/molecule/default/converge.yml
  roles/core/set_hostname/molecule/default/molecule.yml
  roles/core/set_hostname/molecule/default/verify.yml
Labels: ci/cd

#446 Feat: addons/lvm
  CHANGELOG.md
  resources/documentation/roles.rst
  resources/documentation/stories.rst
  resources/packaging/bluebanquise.spec
  roles/addons/lvm/readme.rst
  roles/addons/lvm/tasks/main.yml
  roles/addons/lvm/vars/main.yml
Labels: enhancement

#504 Feat: addons/nic_nmcli - Update routes, add zones
  roles/addons/nic_nmcli/readme.rst
  roles/addons/nic_nmcli/tasks/main.yml
  roles/addons/nic_nmcli/vars/main.yml
Labels: enhancement

#496 Change /etc/conman.conf file mode to 600 to avoid security risks
  CHANGELOG.md
  roles/core/conman/handlers/main.yml
  roles/core/conman/molecule/default/verify.yml
  roles/core/conman/readme.rst
  roles/core/conman/tasks/main.yml
  roles/core/conman/vars/main.yml
Labels: bug

#514 Fix: core/pxe_stack - Update bootset configuration path
  CHANGELOG.md
  resources/documentation/deploy_bluebanquise.rst
  roles/core/pxe_stack/files/bootset.py
  roles/core/pxe_stack/molecule/default/verify.yml
  roles/core/pxe_stack/readme.rst
  roles/core/pxe_stack/tasks/main.yml
Labels: bug

#517 Fix: core/pxe_stack - Fix bad hostname issue
  roles/core/pxe_stack/templates/kickstart.cfg.j2
Labels: bug
