Repository bluebanquise/bluebanquise, pull requests merged in 2021-02, with the labels that each got.

#503 ci: fix some issues with GitHub Actions
  .github/workflows/molecule-actions-core-repositories_client.yml
  roles/core/ssh_master/molecule/default/molecule.yml
Labels: ci/cd, needs-backport

#522 Fix: pxe_stack - Forcing hostname via kernel command
  CHANGELOG.md
  roles/core/pxe_stack/files/osdeploy/centos_7.ipxe
  roles/core/pxe_stack/files/osdeploy/centos_8.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_7.ipxe
  roles/core/pxe_stack/files/osdeploy/redhat_8.ipxe
  roles/core/pxe_stack/templates/kickstart.cfg.j2
Labels: bug, enhancement

#527 Fix ansible modules documentation URL
  resources/documentation/learn_ansible.rst
Labels: bug, documentation

#525 Fix issues found when booting a diskless livenet image
  CHANGELOG.md
  roles/addons/diskless/files/livenet_module.py
Labels: bug, needs-backport

#529 Fix: README - Update
  README.md
Labels: documentation

#533 fix:: unpredictable modules order in disklessset
  roles/addons/diskless/files/image_manager.py
Labels: bug, needs-backport
