Repository bluebanquise/bluebanquise, pull requests merged in 2025-03, with the labels that each got.

#1015 Feat: allow to use hw for partitioning along os
  CHANGELOG
  collections/infrastructure/galaxy.yml
  collections/infrastructure/roles/pxe_stack/templates/Debian/preseed.cfg.j2
  collections/infrastructure/roles/pxe_stack/templates/RedHat/kickstart.cfg.j2
  collections/infrastructure/roles/pxe_stack/templates/Suse/autoyast.xml.j2
  collections/infrastructure/roles/pxe_stack/templates/Ubuntu/user-data.j2
Labels: enhancement, 3.0

#1035 Feat: rasdaemon: Added gigabyte dimm labels
  collections/infrastructure/roles/rasdaemon/files/labels_gigabyte_cer_blade
  collections/infrastructure/roles/rasdaemon/tasks/main.yml
Labels: SMC

#1030 Fix: grafana: better variable and hide admin password from output
  CHANGELOG
  collections/infrastructure/roles/grafana/README.md
  collections/infrastructure/roles/grafana/tasks/main.yml
  collections/infrastructure/roles/grafana/vars/main.yml
Labels: SMC

#1049 BB-51 - Fix critical error in core
  CHANGELOG
  README.md
  collections/infrastructure/galaxy.yml
  collections/infrastructure/plugins/vars/core.py
  resources/bb_core.yml
Labels: bug, 3.0

#1053 Cherry pick/pxe stack
  collections/infrastructure/galaxy.yml
  collections/infrastructure/roles/pxe_stack/README.md
  collections/infrastructure/roles/pxe_stack/templates/RedHat/equipment_profile_ks.ipxe.j2
  tutorials/docs/sysadmin_servers_farm_deployment.md
Labels: 2.0, SMC

#1044 Feat: dns_server: simple dnssec
  CHANGELOG
  collections/infrastructure/roles/dns_server/README.md
  collections/infrastructure/roles/dns_server/defaults/main.yml
  collections/infrastructure/roles/dns_server/tasks/main.yml
  collections/infrastructure/roles/dns_server/tasks/zone_key.yml
  collections/infrastructure/roles/dns_server/templates/forward.j2
  collections/infrastructure/roles/dns_server/templates/named.conf.local.j2
  collections/infrastructure/roles/dns_server/templates/reverse.j2
  collections/infrastructure/roles/dns_server/vars/main.yml
Labels: SMC

#1047 bluebanquise-diskless: apply features done for SMC 1.x, update for BB 3
  collections/infrastructure/roles/pxe_stack/files/bluebanquise-diskless
Labels: SMC

#1045 Fix: pxe_stack - Use aarch64 instead of arm64
  collections/infrastructure/roles/pxe_stack/README.md
  collections/infrastructure/roles/pxe_stack/templates/RedHat/equipment_profile_ks.ipxe.j2
  collections/infrastructure/roles/pxe_stack/vars/main.yml
Labels: SMC

#1054 Fix: grafana - service start in BB3, user creation error
  CHANGELOG
  collections/infrastructure/roles/grafana/README.md
  collections/infrastructure/roles/grafana/handlers/main.yml
  collections/infrastructure/roles/grafana/tasks/install.yml
Labels: SMC

#1056 [FEAT] Monitoring with High Availability and Basic Auth
  collections/infrastructure/roles/prometheus/README.md
  collections/infrastructure/roles/prometheus/defaults/main.yml
  collections/infrastructure/roles/prometheus/files/alertmanager.xml
  collections/infrastructure/roles/prometheus/tasks/server.yml
  collections/infrastructure/roles/prometheus/tasks/server_alertmanager.yml
  collections/infrastructure/roles/prometheus/tasks/server_prometheus.yml
  collections/infrastructure/roles/prometheus/tasks/server_security.yml
  collections/infrastructure/roles/prometheus/templates/alertmanager.service.j2
  collections/infrastructure/roles/prometheus/templates/alertmanager.xml.j2
  collections/infrastructure/roles/prometheus/templates/alertmanager_web.yml.j2
  collections/infrastructure/roles/prometheus/templates/karma.yml.j2
  collections/infrastructure/roles/prometheus/templates/prometheus.yml.j2
  collections/infrastructure/roles/prometheus/templates/prometheus_web.yml.j2
  collections/infrastructure/roles/prometheus/vars/main.yml
Labels: SMC

#1061 Feat: dns_server - round robin load balance
  CHANGELOG
  collections/infrastructure/roles/dns_server/README.md
  collections/infrastructure/roles/dns_server/templates/forward.j2
Labels: SMC

#1059 Feat: dhcp_server - external patterns
  CHANGELOG
  collections/infrastructure/roles/dhcp_server/README.md
  collections/infrastructure/roles/dhcp_server/defaults/main.yml
  collections/infrastructure/roles/dhcp_server/templates/dhcpd.subnet.conf.j2
  collections/infrastructure/roles/dhcp_server/vars/main.yml
Labels: SMC

#1062 Feat: podman - podman registry https support
  CHANGELOG
  collections/infrastructure/roles/podman/README.md
  collections/infrastructure/roles/podman/defaults/main.yml
  collections/infrastructure/roles/podman/tasks/registry.yml
  collections/infrastructure/roles/podman/tasks/registry_encryption.yml
  collections/infrastructure/roles/podman/templates/etc/containers/registries.conf.j2
  collections/infrastructure/roles/podman/templates/registry.service.j2
  collections/infrastructure/roles/podman/vars/main.yml
Labels: SMC
